# Copyright 2026 EcoFuture Technology Services LLC and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by Django 6.0.1 on 2026-01-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='fast_start__autogen_8f29b0_gin',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='fast_start__autogen_d4ae23_gin',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='fast_start__autogen_fb1ce4_gin',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='fast_start__autogen_c7630f_gin',
        ),
        migrations.AlterField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='fast_start.shop', verbose_name='Shop'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='autogen_author_selectors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='autogen_author_updated_selectors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='autogen_delivery_company_selectors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='autogen_shop_selectors',
        ),
    ]
